### ISSUE TITLE
arch: Protect schemas with key names of reserved keywords

### ISSUE THREAD

**Issue by sthzg** [sthzg/jsugen#41]
Examples

```yaml
type: object
properties:
  properties:
    type: object
    properties:
       ...

type: object
properties:
  items:
    type: array  
    items:
      type: object
      properties:
        ...
```
